name: Deploy - Backend

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Add environment variables to .env file
        run: |
          echo "MONGO_INITDB_ROOT_USERNAME={{ secrets.MONGO_INITDB_ROOT_USERNAME }}" >> .env
          echo "MONGO_INITDB_ROOT_PASSWORD={{ secrets.MONGO_INITDB_ROOT_PASSWORD }}" >> .env
          echo "MONGO_INITDB_DATABASE={{ secrets.MONGO_INITDB_DATABASE }}" >> .env
          echo "MONGO_INITDB_PORT={{ secrets.MONGO_INITDB_PORT }}" >> .env
          echo "MONGO_INITDB_COLLECTION_USER={{ secrets.MONGO_INITDB_COLLECTION_USER }}" >> .env
          echo "MONGO_INITDB_COLLECTION_OCR={{ secrets.MONGO_INITDB_COLLECTION_OCR }}" >> .env
          echo "ACCESS_TOKEN_EXPIRES_IN={{ secrets.ACCESS_TOKEN_EXPIRES_IN }}" >> .env
          echo "REFRESH_TOKEN_EXPIRES_IN={{ secrets.REFRESH_TOKEN_EXPIRES_IN }}" >> .env
          echo "JWT_ALGORITHM={{ secrets.JWT_ALGORITHM }}" >> .env
          echo "CLIENT_ORIGIN={{ secrets.CLIENT_ORIGIN }}" >> .env
          echo "EMAIL_HOST={{ secrets.EMAIL_HOST }}" >> .env
          echo "EMAIL_PORT={{ secrets.EMAIL_PORT }}" >> .env
          echo "EMAIL_USER={{ secrets.EMAIL_USER }}" >>.env
          echo "EMAIL_PASSWORD={{ secrets.EMAIL_PASSWORD }} >>.env
          echo "EMAIL_FROM={{ secrets.EMAIL_FROM }} >>.env
          echo "EMAIL_JWT_PRIVATE_KEY={{ secrets.EMAIL_JWT_PRIVATE_KEY }} >>.env
          echo "EMAIL_JWT_PUBLIC_KEY={{ secrets.EMAIL_JWT_PUBLIC_KEY }} >>.env



      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }}:latest
      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Push image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }}:latest


